GET http://localhost:3000/api
Content-Type: application/json

###

POST http://localhost:3000/api
Content-Type: application/json

{
  "nik": "17022047",
  "namaAwal": "Erehh",
  "namaAkhir": "Iyegeeh",
  "umur": 20,
  "posisi": "ngerumbling"
}

###

PUT http://localhost:3000/api?nik=17022047
Content-Type: application/json

{
  "nik": "17022048",
  "namaAwal": "Febri",
  "namaAkhir": "Adji",
  "umur": 19,
  "posisi": "fullstack developer"
}

###

DELETE http://localhost:3000/api
Content-Type: application/json

{ "nik": "17022047" }